<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 16 Generalized Linear Models | Data Science for Biologists - 5023Y</title>
  <meta name="description" content="This is very brief introduction to some of the basic skills required to learn R" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 16 Generalized Linear Models | Data Science for Biologists - 5023Y" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is very brief introduction to some of the basic skills required to learn R" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 16 Generalized Linear Models | Data Science for Biologists - 5023Y" />
  
  <meta name="twitter:description" content="This is very brief introduction to some of the basic skills required to learn R" />
  

<meta name="author" content="Philip Leftwich" />


<meta name="date" content="2022-03-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="complexity-in-linear-models---spring-week-seven.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.12.2/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#approach-and-style"><i class="fa fa-check"></i><b>1.1</b> Approach and style<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#teaching"><i class="fa fa-check"></i><b>1.2</b> Teaching<span></span></a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#workshops"><i class="fa fa-check"></i><b>1.2.1</b> Workshops<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#introduction-to-r"><i class="fa fa-check"></i><b>1.3</b> Introduction to R<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#getting-around-on-rstudio"><i class="fa fa-check"></i><b>1.4</b> Getting around on RStudio<span></span></a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#an-intro-to-rstudio"><i class="fa fa-check"></i><b>1.4.1</b> An intro to RStudio<span></span></a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#using-r-studio-cloud"><i class="fa fa-check"></i><b>1.4.2</b> Using R Studio Cloud<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#reading"><i class="fa fa-check"></i><b>1.5</b> Reading<span></span></a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#get-help"><i class="fa fa-check"></i><b>1.6</b> Get Help!<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html"><i class="fa fa-check"></i><b>2</b> Getting to know R: Week One<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#your-first-r-command"><i class="fa fa-check"></i><b>2.1</b> Your first R command<span></span></a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#typos"><i class="fa fa-check"></i><b>2.1.1</b> Typos<span></span></a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#more-simple-arithmetic"><i class="fa fa-check"></i><b>2.1.2</b> More simple arithmetic<span></span></a></li>
<li class="chapter" data-level="2.1.3" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#try-some-maths"><i class="fa fa-check"></i><b>2.1.3</b> Try some maths<span></span></a></li>
<li class="chapter" data-level="2.1.4" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#perform-some-combos"><i class="fa fa-check"></i><b>2.1.4</b> Perform some combos<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#true-or-false-data"><i class="fa fa-check"></i><b>2.2</b> “true or false” data<span></span></a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#assessing-mathematical-truths"><i class="fa fa-check"></i><b>2.2.1</b> Assessing mathematical truths<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#storing-outputs"><i class="fa fa-check"></i><b>2.3</b> Storing outputs<span></span></a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#choosing-names"><i class="fa fa-check"></i><b>2.3.1</b> Choosing names<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#writing-scripts"><i class="fa fa-check"></i><b>2.4</b> Writing scripts<span></span></a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#commenting-on-scripts"><i class="fa fa-check"></i><b>2.4.1</b> Commenting on scripts<span></span></a></li>
<li class="chapter" data-level="2.4.2" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#running-your-script"><i class="fa fa-check"></i><b>2.4.2</b> Running your script<span></span></a></li>
<li class="chapter" data-level="2.4.3" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#saving-your-script"><i class="fa fa-check"></i><b>2.4.3</b> Saving your script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#error"><i class="fa fa-check"></i><b>2.5</b> Error<span></span></a></li>
<li class="chapter" data-level="2.6" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#functions"><i class="fa fa-check"></i><b>2.6</b> Functions<span></span></a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#storing-the-output-of-functions"><i class="fa fa-check"></i><b>2.6.1</b> Storing the output of functions<span></span></a></li>
<li class="chapter" data-level="2.6.2" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#more-fun-with-functions"><i class="fa fa-check"></i><b>2.6.2</b> More fun with functions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#packages"><i class="fa fa-check"></i><b>2.7</b> Packages<span></span></a></li>
<li class="chapter" data-level="2.8" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#my-first-data-visualisation"><i class="fa fa-check"></i><b>2.8</b> My first data visualisation<span></span></a></li>
<li class="chapter" data-level="2.9" data-path="getting-to-know-r-week-one.html"><a href="getting-to-know-r-week-one.html#quitting"><i class="fa fa-check"></i><b>2.9</b> Quitting<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html"><i class="fa fa-check"></i><b>3</b> Workflow Part One: Week Two<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#meet-the-penguins"><i class="fa fa-check"></i><b>3.1</b> Meet the Penguins<span></span></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#insights-from-data"><i class="fa fa-check"></i><b>3.1.1</b> Insights from data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#the-question"><i class="fa fa-check"></i><b>3.2</b> The Question?<span></span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#hypotheses"><i class="fa fa-check"></i><b>3.2.1</b> Hypotheses<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#preparing-the-data"><i class="fa fa-check"></i><b>3.3</b> Preparing the data<span></span></a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#tidy-data"><i class="fa fa-check"></i><b>3.3.1</b> Tidy data<span></span></a></li>
<li class="chapter" data-level="3.3.2" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#the-dataset"><i class="fa fa-check"></i><b>3.3.2</b> The dataset<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#prepare-the-rstudio-workspace"><i class="fa fa-check"></i><b>3.4</b> Prepare the RStudio workspace<span></span></a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#organise"><i class="fa fa-check"></i><b>3.4.1</b> Organise<span></span></a></li>
<li class="chapter" data-level="3.4.2" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#create-a-new-r-script"><i class="fa fa-check"></i><b>3.4.2</b> Create a new R script<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#get-the-data-into-r"><i class="fa fa-check"></i><b>3.5</b> Get the data into R<span></span></a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#view-and-refine"><i class="fa fa-check"></i><b>3.5.1</b> View and refine<span></span></a></li>
<li class="chapter" data-level="3.5.2" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#data-management"><i class="fa fa-check"></i><b>3.5.2</b> Data management<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#dataframes-and-tibbles"><i class="fa fa-check"></i><b>3.6</b> Dataframes and tibbles<span></span></a></li>
<li class="chapter" data-level="3.7" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#clean-and-tidy"><i class="fa fa-check"></i><b>3.7</b> Clean and tidy<span></span></a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#tidy"><i class="fa fa-check"></i><b>3.7.1</b> Tidy<span></span></a></li>
<li class="chapter" data-level="3.7.2" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#clean"><i class="fa fa-check"></i><b>3.7.2</b> Clean<span></span></a></li>
<li class="chapter" data-level="3.7.3" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#refine-variable-names"><i class="fa fa-check"></i><b>3.7.3</b> Refine variable names<span></span></a></li>
<li class="chapter" data-level="3.7.4" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#dates"><i class="fa fa-check"></i><b>3.7.4</b> Dates<span></span></a></li>
<li class="chapter" data-level="3.7.5" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#rename-some-values"><i class="fa fa-check"></i><b>3.7.5</b> Rename some values<span></span></a></li>
<li class="chapter" data-level="3.7.6" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#check-for-duplication"><i class="fa fa-check"></i><b>3.7.6</b> Check for duplication<span></span></a></li>
<li class="chapter" data-level="3.7.7" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#check-for-typos-or-implausible-values"><i class="fa fa-check"></i><b>3.7.7</b> Check for typos or implausible values<span></span></a></li>
<li class="chapter" data-level="3.7.8" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#missing-values-na"><i class="fa fa-check"></i><b>3.7.8</b> Missing values: NA<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#summing-up"><i class="fa fa-check"></i><b>3.8</b> Summing up<span></span></a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#what-we-learned"><i class="fa fa-check"></i><b>3.8.1</b> What we learned<span></span></a></li>
<li class="chapter" data-level="3.8.2" data-path="workflow-part-one-week-two.html"><a href="workflow-part-one-week-two.html#quitting-1"><i class="fa fa-check"></i><b>3.8.2</b> Quitting<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html"><i class="fa fa-check"></i><b>4</b> Workflow Part Two: Week Three<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#initial-insights"><i class="fa fa-check"></i><b>4.1</b> Initial insights<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#numbers-and-sex-of-the-penguins"><i class="fa fa-check"></i><b>4.2</b> Numbers and sex of the penguins<span></span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#making-a-simple-figure"><i class="fa fa-check"></i><b>4.2.1</b> Making a simple figure<span></span></a></li>
<li class="chapter" data-level="4.2.2" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#challenge"><i class="fa fa-check"></i><b>4.2.2</b> Challenge<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#distributions"><i class="fa fa-check"></i><b>4.3</b> Distributions<span></span></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#insights"><i class="fa fa-check"></i><b>4.3.1</b> Insights<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#more-distributions"><i class="fa fa-check"></i><b>4.4</b> More distributions<span></span></a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#initial-conclusions"><i class="fa fa-check"></i><b>4.4.1</b> Initial conclusions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#data-transformation"><i class="fa fa-check"></i><b>4.5</b> Data transformation<span></span></a></li>
<li class="chapter" data-level="4.6" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#developing-insights"><i class="fa fa-check"></i><b>4.6</b> Developing insights<span></span></a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#distributions-of-the-relative-bill-length"><i class="fa fa-check"></i><b>4.6.1</b> Distributions of the relative bill length<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#relationshipdifferences"><i class="fa fa-check"></i><b>4.7</b> Relationship/differences<span></span></a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#differences"><i class="fa fa-check"></i><b>4.7.1</b> Differences<span></span></a></li>
<li class="chapter" data-level="4.7.2" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#associations"><i class="fa fa-check"></i><b>4.7.2</b> Associations<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#sex-interactions"><i class="fa fa-check"></i><b>4.8</b> Sex interactions<span></span></a></li>
<li class="chapter" data-level="4.9" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#making-our-graphs-more-attractive"><i class="fa fa-check"></i><b>4.9</b> Making our graphs more attractive<span></span></a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#saving-your-output"><i class="fa fa-check"></i><b>4.9.1</b> Saving your output<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="workflow-part-two-week-three.html"><a href="workflow-part-two-week-three.html#quitting-2"><i class="fa fa-check"></i><b>4.10</b> Quitting<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html"><i class="fa fa-check"></i><b>5</b> ggplot2 A grammar of graphics: Week Four<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#intro-to-grammar"><i class="fa fa-check"></i><b>5.1</b> Intro to grammar<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#building-a-plot"><i class="fa fa-check"></i><b>5.2</b> Building a plot<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#plot-background"><i class="fa fa-check"></i><b>5.3</b> Plot background<span></span></a></li>
<li class="chapter" data-level="5.4" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#aesthetics---aes"><i class="fa fa-check"></i><b>5.4</b> Aesthetics - aes()<span></span></a></li>
<li class="chapter" data-level="5.5" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#geometric-representations---geom"><i class="fa fa-check"></i><b>5.5</b> Geometric representations - geom()<span></span></a></li>
<li class="chapter" data-level="5.6" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#and"><i class="fa fa-check"></i><b>5.6</b> %&gt;% and +<span></span></a></li>
<li class="chapter" data-level="5.7" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#colour"><i class="fa fa-check"></i><b>5.7</b> Colour<span></span></a></li>
<li class="chapter" data-level="5.8" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#more-layers"><i class="fa fa-check"></i><b>5.8</b> More layers<span></span></a></li>
<li class="chapter" data-level="5.9" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#facets"><i class="fa fa-check"></i><b>5.9</b> Facets<span></span></a></li>
<li class="chapter" data-level="5.10" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#co-ordinate-space"><i class="fa fa-check"></i><b>5.10</b> Co-ordinate space<span></span></a></li>
<li class="chapter" data-level="5.11" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#labels"><i class="fa fa-check"></i><b>5.11</b> Labels<span></span></a></li>
<li class="chapter" data-level="5.12" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#themes"><i class="fa fa-check"></i><b>5.12</b> Themes<span></span></a></li>
<li class="chapter" data-level="5.13" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#jitter"><i class="fa fa-check"></i><b>5.13</b> Jitter<span></span></a></li>
<li class="chapter" data-level="5.14" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#boxplots"><i class="fa fa-check"></i><b>5.14</b> Boxplots<span></span></a></li>
<li class="chapter" data-level="5.15" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#density-and-histogram"><i class="fa fa-check"></i><b>5.15</b> Density and histogram<span></span></a></li>
<li class="chapter" data-level="5.16" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#more-colours"><i class="fa fa-check"></i><b>5.16</b> More Colours<span></span></a>
<ul>
<li class="chapter" data-level="5.16.1" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#assign-colours-to-variables"><i class="fa fa-check"></i><b>5.16.1</b> Assign colours to variables<span></span></a></li>
<li class="chapter" data-level="5.16.2" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#accessibility"><i class="fa fa-check"></i><b>5.16.2</b> Accessibility<span></span></a></li>
<li class="chapter" data-level="5.16.3" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#guides-to-visual-accessibility"><i class="fa fa-check"></i><b>5.16.3</b> Guides to visual accessibility<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.17" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#patchwork"><i class="fa fa-check"></i><b>5.17</b> Patchwork<span></span></a></li>
<li class="chapter" data-level="5.18" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#test"><i class="fa fa-check"></i><b>5.18</b> Test<span></span></a></li>
<li class="chapter" data-level="5.19" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#saving"><i class="fa fa-check"></i><b>5.19</b> Saving<span></span></a></li>
<li class="chapter" data-level="5.20" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#quitting-3"><i class="fa fa-check"></i><b>5.20</b> Quitting<span></span></a></li>
<li class="chapter" data-level="5.21" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#summing-up-ggplot"><i class="fa fa-check"></i><b>5.21</b> Summing up ggplot<span></span></a>
<ul>
<li class="chapter" data-level="5.21.1" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#what-we-learned-1"><i class="fa fa-check"></i><b>5.21.1</b> What we learned<span></span></a></li>
<li class="chapter" data-level="5.21.2" data-path="ggplot2-a-grammar-of-graphics-week-four.html"><a href="ggplot2-a-grammar-of-graphics-week-four.html#further-reading-guides-and-tips"><i class="fa fa-check"></i><b>5.21.2</b> Further Reading, Guides and tips<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html"><i class="fa fa-check"></i><b>6</b> Reports with Rmarkdown: Week Five<span></span></a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#format"><i class="fa fa-check"></i><b>6.0.1</b> Format<span></span></a></li>
<li class="chapter" data-level="6.1" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#background-to-rmarkdown"><i class="fa fa-check"></i><b>6.1</b> Background to Rmarkdown<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#starting-a-new-rmd-file"><i class="fa fa-check"></i><b>6.2</b> Starting a new Rmd file<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#r-markdown-parts"><i class="fa fa-check"></i><b>6.3</b> R Markdown parts<span></span></a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#yaml"><i class="fa fa-check"></i><b>6.3.1</b> YAML<span></span></a></li>
<li class="chapter" data-level="6.3.2" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#text"><i class="fa fa-check"></i><b>6.3.2</b> Text<span></span></a></li>
<li class="chapter" data-level="6.3.3" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#code-chunks"><i class="fa fa-check"></i><b>6.3.3</b> Code Chunks<span></span></a></li>
<li class="chapter" data-level="6.3.4" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#here"><i class="fa fa-check"></i><b>6.3.4</b> Here<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#images"><i class="fa fa-check"></i><b>6.4</b> Images<span></span></a></li>
<li class="chapter" data-level="6.5" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#tables"><i class="fa fa-check"></i><b>6.5</b> Tables<span></span></a></li>
<li class="chapter" data-level="6.6" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#self-contained-documents"><i class="fa fa-check"></i><b>6.6</b> Self-contained documents<span></span></a></li>
<li class="chapter" data-level="6.7" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#source-files"><i class="fa fa-check"></i><b>6.7</b> Source files<span></span></a></li>
<li class="chapter" data-level="6.8" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#exercise---make-your-own-rmd-document"><i class="fa fa-check"></i><b>6.8</b> Exercise - Make your own Rmd document<span></span></a></li>
<li class="chapter" data-level="6.9" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#summing-up-rmarkdown"><i class="fa fa-check"></i><b>6.9</b> Summing up Rmarkdown<span></span></a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#what-we-learned-2"><i class="fa fa-check"></i><b>6.9.1</b> What we learned<span></span></a></li>
<li class="chapter" data-level="6.9.2" data-path="reports-with-rmarkdown-week-five.html"><a href="reports-with-rmarkdown-week-five.html#further-reading-guides-and-tips-1"><i class="fa fa-check"></i><b>6.9.2</b> Further Reading, Guides and tips<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html"><i class="fa fa-check"></i><b>7</b> Version control with GitHub: Week Six<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#lets-git-it-started"><i class="fa fa-check"></i><b>7.1</b> Let’s Git it started<span></span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#will-this-be-fun"><i class="fa fa-check"></i><b>7.1.1</b> Will this be fun?<span></span></a></li>
<li class="chapter" data-level="7.1.2" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#the-payoff"><i class="fa fa-check"></i><b>7.1.2</b> The Payoff<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#set-up-github"><i class="fa fa-check"></i><b>7.2</b> Set up GitHub<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#exercise-1.-fork-clone-an-existing-repo-on-github-make-edits-push-back"><i class="fa fa-check"></i><b>7.3</b> <strong>Exercise 1.</strong> Fork &amp; clone an existing repo on GitHub, make edits, push back<span></span></a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#what-the-hell-is-a-fork"><i class="fa fa-check"></i><b>7.3.1</b> What the hell is a fork?<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#talking-to-github"><i class="fa fa-check"></i><b>7.4</b> Talking to GitHub<span></span></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#see-changes"><i class="fa fa-check"></i><b>7.4.1</b> See changes<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#how-to-use-version-control---when-to-commit-push-and-pull"><i class="fa fa-check"></i><b>7.5</b> How to use version control - when to commit, push and pull<span></span></a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#commit"><i class="fa fa-check"></i><b>7.5.1</b> Commit<span></span></a></li>
<li class="chapter" data-level="7.5.2" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#push"><i class="fa fa-check"></i><b>7.5.2</b> Push<span></span></a></li>
<li class="chapter" data-level="7.5.3" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#a-couple-of-general-tips"><i class="fa fa-check"></i><b>7.5.3</b> A couple of general tips:<span></span></a></li>
<li class="chapter" data-level="7.5.4" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#turn-back-time-with-git"><i class="fa fa-check"></i><b>7.5.4</b> Turn back time with Git<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#exercise-2.-github-classrooms-enabled-r-projects-with-subfolders"><i class="fa fa-check"></i><b>7.6</b> <strong>Exercise 2.</strong> GitHub Classrooms enabled R Projects with subfolders<span></span></a></li>
<li class="chapter" data-level="7.7" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#find-your-classroom-repos"><i class="fa fa-check"></i><b>7.7</b> Find your classroom repos<span></span></a></li>
<li class="chapter" data-level="7.8" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#glossary-github"><i class="fa fa-check"></i><b>7.8</b> Glossary-GitHub<span></span></a></li>
<li class="chapter" data-level="7.9" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#summing-up-github"><i class="fa fa-check"></i><b>7.9</b> Summing up GitHub<span></span></a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#what-we-learned-3"><i class="fa fa-check"></i><b>7.9.1</b> What we learned<span></span></a></li>
<li class="chapter" data-level="7.9.2" data-path="version-control-with-github-week-six.html"><a href="version-control-with-github-week-six.html#further-reading-guides-and-tips-2"><i class="fa fa-check"></i><b>7.9.2</b> Further Reading, Guides and tips<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html"><i class="fa fa-check"></i><b>8</b> Dealing with data: dplyr: Week Eight<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#lets-get-going"><i class="fa fa-check"></i><b>8.1</b> Let’s get going<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#introduction-to-dplyr"><i class="fa fa-check"></i><b>8.2</b> Introduction to dplyr<span></span></a></li>
<li class="chapter" data-level="8.3" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#select"><i class="fa fa-check"></i><b>8.3</b> select<span></span></a></li>
<li class="chapter" data-level="8.4" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#mutate"><i class="fa fa-check"></i><b>8.4</b> mutate<span></span></a></li>
<li class="chapter" data-level="8.5" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#filter"><i class="fa fa-check"></i><b>8.5</b> filter<span></span></a></li>
<li class="chapter" data-level="8.6" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#arrange"><i class="fa fa-check"></i><b>8.6</b> arrange<span></span></a></li>
<li class="chapter" data-level="8.7" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#group-and-summarise"><i class="fa fa-check"></i><b>8.7</b> Group and summarise<span></span></a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#using-summarise"><i class="fa fa-check"></i><b>8.7.1</b> Using summarise<span></span></a></li>
<li class="chapter" data-level="8.7.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#summarize-all-columns"><i class="fa fa-check"></i><b>8.7.2</b> Summarize all columns<span></span></a></li>
<li class="chapter" data-level="8.7.3" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#group_by-summary"><i class="fa fa-check"></i><b>8.7.3</b> group_by summary<span></span></a></li>
<li class="chapter" data-level="8.7.4" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#more-than-one-grouping-variable"><i class="fa fa-check"></i><b>8.7.4</b> More than one grouping variable<span></span></a></li>
<li class="chapter" data-level="8.7.5" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#remove-group_by"><i class="fa fa-check"></i><b>8.7.5</b> remove group_by<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#expanding-the-data-toolkit"><i class="fa fa-check"></i><b>8.8</b> Expanding the data toolkit<span></span></a></li>
<li class="chapter" data-level="8.9" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#pipes"><i class="fa fa-check"></i><b>8.9</b> Pipes<span></span></a></li>
<li class="chapter" data-level="8.10" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#strings"><i class="fa fa-check"></i><b>8.10</b> Strings<span></span></a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#separate"><i class="fa fa-check"></i><b>8.10.1</b> separate<span></span></a></li>
<li class="chapter" data-level="8.10.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#more-stringr"><i class="fa fa-check"></i><b>8.10.2</b> More stringr<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#dates-and-times"><i class="fa fa-check"></i><b>8.11</b> Dates and times<span></span></a>
<ul>
<li class="chapter" data-level="8.11.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#calculations-with-dates"><i class="fa fa-check"></i><b>8.11.1</b> Calculations with dates<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#pivot"><i class="fa fa-check"></i><b>8.12</b> Pivot<span></span></a></li>
<li class="chapter" data-level="8.13" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#summing-up-1"><i class="fa fa-check"></i><b>8.13</b> Summing up<span></span></a>
<ul>
<li class="chapter" data-level="8.13.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#what-we-learned-4"><i class="fa fa-check"></i><b>8.13.1</b> What we learned<span></span></a></li>
<li class="chapter" data-level="8.13.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#further-reading-guides-and-tips-3"><i class="fa fa-check"></i><b>8.13.2</b> Further Reading, Guides and tips<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.14" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#variables"><i class="fa fa-check"></i><b>8.14</b> Variables<span></span></a>
<ul>
<li class="chapter" data-level="8.14.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#numerical"><i class="fa fa-check"></i><b>8.14.1</b> Numerical<span></span></a></li>
<li class="chapter" data-level="8.14.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#categorical"><i class="fa fa-check"></i><b>8.14.2</b> Categorical<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.15" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#understanding-numerical-variables"><i class="fa fa-check"></i><b>8.15</b> Understanding Numerical variables<span></span></a>
<ul>
<li class="chapter" data-level="8.15.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#graphing-a-numeric-variable"><i class="fa fa-check"></i><b>8.15.1</b> Graphing a numeric variable<span></span></a></li>
<li class="chapter" data-level="8.15.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#insights-about-body-mass"><i class="fa fa-check"></i><b>8.15.2</b> Insights about body mass<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.16" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#descriptive-statistics"><i class="fa fa-check"></i><b>8.16</b> Descriptive statistics<span></span></a>
<ul>
<li class="chapter" data-level="8.16.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#central-tendency"><i class="fa fa-check"></i><b>8.16.1</b> Central tendency<span></span></a></li>
<li class="chapter" data-level="8.16.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#dispersion"><i class="fa fa-check"></i><b>8.16.2</b> Dispersion<span></span></a></li>
<li class="chapter" data-level="8.16.3" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#visualising-dispersion"><i class="fa fa-check"></i><b>8.16.3</b> Visualising dispersion<span></span></a></li>
<li class="chapter" data-level="8.16.4" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#combining-histograms-and-boxplots"><i class="fa fa-check"></i><b>8.16.4</b> Combining histograms and boxplots<span></span></a></li>
<li class="chapter" data-level="8.16.5" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#missing-values"><i class="fa fa-check"></i><b>8.16.5</b> Missing values<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.17" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#categorical-variables"><i class="fa fa-check"></i><b>8.17</b> Categorical variables<span></span></a>
<ul>
<li class="chapter" data-level="8.17.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#summaries"><i class="fa fa-check"></i><b>8.17.1</b> Summaries<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.18" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#summing-up-2"><i class="fa fa-check"></i><b>8.18</b> Summing up<span></span></a>
<ul>
<li class="chapter" data-level="8.18.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#reward"><i class="fa fa-check"></i><b>8.18.1</b> Reward<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.19" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#associations-between-numerical-variables"><i class="fa fa-check"></i><b>8.19</b> Associations between numerical variables<span></span></a>
<ul>
<li class="chapter" data-level="8.19.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#correlations"><i class="fa fa-check"></i><b>8.19.1</b> Correlations<span></span></a></li>
<li class="chapter" data-level="8.19.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#non-linear-correlations"><i class="fa fa-check"></i><b>8.19.2</b> Non-linear correlations<span></span></a></li>
<li class="chapter" data-level="8.19.3" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#graphical-summaries-between-numeric-variables"><i class="fa fa-check"></i><b>8.19.3</b> Graphical summaries between numeric variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.20" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>8.20</b> Associations between categorical variables<span></span></a></li>
<li class="chapter" data-level="8.21" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#associations-between-categorical-numerical-variables"><i class="fa fa-check"></i><b>8.21</b> Associations between Categorical-numerical variables<span></span></a></li>
<li class="chapter" data-level="8.22" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#complexity"><i class="fa fa-check"></i><b>8.22</b> Complexity<span></span></a>
<ul>
<li class="chapter" data-level="8.22.1" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#simpsons-paradox"><i class="fa fa-check"></i><b>8.22.1</b> Simpson’s Paradox<span></span></a></li>
<li class="chapter" data-level="8.22.2" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#three-or-more-variables"><i class="fa fa-check"></i><b>8.22.2</b> Three or more variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.23" data-path="dealing-with-data-dplyr-week-eight.html"><a href="dealing-with-data-dplyr-week-eight.html#summing-up-3"><i class="fa fa-check"></i><b>8.23</b> Summing up<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html"><i class="fa fa-check"></i><b>9</b> Introduction to Statistics - Spring Week One<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#introduction-to-statistics"><i class="fa fa-check"></i><b>9.1</b> Introduction to statistics<span></span></a></li>
<li class="chapter" data-level="9.2" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#darwins-maize-data"><i class="fa fa-check"></i><b>9.2</b> Darwin’s maize data<span></span></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#description"><i class="fa fa-check"></i><b>9.2.1</b> Description<span></span></a></li>
<li class="chapter" data-level="9.2.2" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#visualisation"><i class="fa fa-check"></i><b>9.2.2</b> Visualisation<span></span></a></li>
<li class="chapter" data-level="9.2.3" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#comparing-groups"><i class="fa fa-check"></i><b>9.2.3</b> Comparing groups<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#estimation"><i class="fa fa-check"></i><b>9.3</b> Estimation<span></span></a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#differences-between-groups"><i class="fa fa-check"></i><b>9.3.1</b> Differences between groups<span></span></a></li>
<li class="chapter" data-level="9.3.2" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#standard-error-of-the-difference"><i class="fa fa-check"></i><b>9.3.2</b> Standard error of the difference<span></span></a></li>
<li class="chapter" data-level="9.3.3" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#normal-distribution"><i class="fa fa-check"></i><b>9.3.3</b> Normal distribution<span></span></a></li>
<li class="chapter" data-level="9.3.4" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#confidence-intervals"><i class="fa fa-check"></i><b>9.3.4</b> Confidence Intervals<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#summary"><i class="fa fa-check"></i><b>9.4</b> Summary<span></span></a></li>
<li class="chapter" data-level="9.5" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#functions-1"><i class="fa fa-check"></i><b>9.5</b> Functions<span></span></a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#common-functions"><i class="fa fa-check"></i><b>9.5.1</b> Common functions<span></span></a></li>
<li class="chapter" data-level="9.5.2" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#write-your-own-function"><i class="fa fa-check"></i><b>9.5.2</b> Write your own function<span></span></a></li>
<li class="chapter" data-level="9.5.3" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#more-functions"><i class="fa fa-check"></i><b>9.5.3</b> More functions<span></span></a></li>
<li class="chapter" data-level="9.5.4" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#exercise"><i class="fa fa-check"></i><b>9.5.4</b> Exercise<span></span></a></li>
<li class="chapter" data-level="9.5.5" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#custom-ggplot-themes"><i class="fa fa-check"></i><b>9.5.5</b> Custom ggplot themes<span></span></a></li>
<li class="chapter" data-level="9.5.6" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#writing-packages"><i class="fa fa-check"></i><b>9.5.6</b> Writing Packages<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#iteration"><i class="fa fa-check"></i><b>9.6</b> Iteration<span></span></a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#for-loops"><i class="fa fa-check"></i><b>9.6.1</b> For Loops<span></span></a></li>
<li class="chapter" data-level="9.6.2" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#exercise-for-for-loops"><i class="fa fa-check"></i><b>9.6.2</b> Exercise for For Loops<span></span></a></li>
<li class="chapter" data-level="9.6.3" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#iteration-in-r"><i class="fa fa-check"></i><b>9.6.3</b> Iteration in R<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#more-practice"><i class="fa fa-check"></i><b>9.7</b> More Practice<span></span></a></li>
<li class="chapter" data-level="9.8" data-path="introduction-to-statistics---spring-week-one.html"><a href="introduction-to-statistics---spring-week-one.html#summary-1"><i class="fa fa-check"></i><b>9.8</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html"><i class="fa fa-check"></i><b>10</b> Introduction to Linear Models - Spring Week Two<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#introduction-to-linear-models"><i class="fa fa-check"></i><b>10.1</b> Introduction to Linear Models<span></span></a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#packages-1"><i class="fa fa-check"></i><b>10.1.1</b> Packages<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#a-linear-model-analysis-for-comparing-groups"><i class="fa fa-check"></i><b>10.2</b> A linear model analysis for comparing groups<span></span></a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#compare-means"><i class="fa fa-check"></i><b>10.2.1</b> Compare means<span></span></a></li>
<li class="chapter" data-level="10.2.2" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#standard-error-of-the-difference-1"><i class="fa fa-check"></i><b>10.2.2</b> Standard error of the difference<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#confidence-intervals-1"><i class="fa fa-check"></i><b>10.3</b> Confidence intervals<span></span></a></li>
<li class="chapter" data-level="10.4" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#answering-the-question"><i class="fa fa-check"></i><b>10.4</b> Answering the question<span></span></a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#getting-the-other-treatment-mean-and-standard-error"><i class="fa fa-check"></i><b>10.4.1</b> Getting the other treatment mean and standard error<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#assumption-checking"><i class="fa fa-check"></i><b>10.5</b> Assumption checking<span></span></a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#normal-distribution-1"><i class="fa fa-check"></i><b>10.5.1</b> Normal distribution<span></span></a></li>
<li class="chapter" data-level="10.5.2" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#equal-variance"><i class="fa fa-check"></i><b>10.5.2</b> Equal variance<span></span></a></li>
<li class="chapter" data-level="10.5.3" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#outliers"><i class="fa fa-check"></i><b>10.5.3</b> Outliers<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="introduction-to-linear-models---spring-week-two.html"><a href="introduction-to-linear-models---spring-week-two.html#summary-2"><i class="fa fa-check"></i><b>10.6</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html"><i class="fa fa-check"></i><b>11</b> Testing - Spring Week Three<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#its-t-time"><i class="fa fa-check"></i><b>11.1</b> It’s t-time<span></span></a></li>
<li class="chapter" data-level="11.2" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#students-t-test"><i class="fa fa-check"></i><b>11.2</b> Student’s <em>t</em>-test<span></span></a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#paired-t"><i class="fa fa-check"></i><b>11.2.1</b> Paired t<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#effect-sizes"><i class="fa fa-check"></i><b>11.3</b> Effect sizes<span></span></a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#power"><i class="fa fa-check"></i><b>11.3.1</b> Power<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#meta-analysis"><i class="fa fa-check"></i><b>11.4</b> Meta-analysis<span></span></a></li>
<li class="chapter" data-level="11.5" data-path="testing---spring-week-three.html"><a href="testing---spring-week-three.html#summary-3"><i class="fa fa-check"></i><b>11.5</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html"><i class="fa fa-check"></i><b>12</b> Regression - Spring Week Four<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#introduction-to-regression"><i class="fa fa-check"></i><b>12.1</b> Introduction to Regression<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#linear-regression"><i class="fa fa-check"></i><b>12.2</b> Linear regression<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#data"><i class="fa fa-check"></i><b>12.3</b> Data<span></span></a></li>
<li class="chapter" data-level="12.4" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#correlation"><i class="fa fa-check"></i><b>12.4</b> Correlation<span></span></a></li>
<li class="chapter" data-level="12.5" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#regression-in-r"><i class="fa fa-check"></i><b>12.5</b> Regression in R<span></span></a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#summary-4"><i class="fa fa-check"></i><b>12.5.1</b> Summary<span></span></a></li>
<li class="chapter" data-level="12.5.2" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#the-second-row"><i class="fa fa-check"></i><b>12.5.2</b> the second row<span></span></a></li>
<li class="chapter" data-level="12.5.3" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#confidence-intervals-2"><i class="fa fa-check"></i><b>12.5.3</b> Confidence intervals<span></span></a></li>
<li class="chapter" data-level="12.5.4" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#effect-size"><i class="fa fa-check"></i><b>12.5.4</b> Effect size<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#assumptions"><i class="fa fa-check"></i><b>12.6</b> Assumptions<span></span></a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#normal-distribution-2"><i class="fa fa-check"></i><b>12.6.1</b> Normal distribution<span></span></a></li>
<li class="chapter" data-level="12.6.2" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#equal-variance-1"><i class="fa fa-check"></i><b>12.6.2</b> Equal variance<span></span></a></li>
<li class="chapter" data-level="12.6.3" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#outliers-1"><i class="fa fa-check"></i><b>12.6.3</b> Outliers<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#prediction"><i class="fa fa-check"></i><b>12.7</b> Prediction<span></span></a></li>
<li class="chapter" data-level="12.8" data-path="regression---spring-week-four.html"><a href="regression---spring-week-four.html#summary-5"><i class="fa fa-check"></i><b>12.8</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html"><i class="fa fa-check"></i><b>13</b> ANOVA - Spring Week Five<span></span></a>
<ul>
<li class="chapter" data-level="13.1" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#anova"><i class="fa fa-check"></i><b>13.1</b> ANOVA<span></span></a></li>
<li class="chapter" data-level="13.2" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#maize-data"><i class="fa fa-check"></i><b>13.2</b> Maize data<span></span></a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#the-anova-table"><i class="fa fa-check"></i><b>13.2.1</b> The ANOVA table<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#two-way-anova"><i class="fa fa-check"></i><b>13.3</b> Two-way ANOVA<span></span></a></li>
<li class="chapter" data-level="13.4" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#summary-6"><i class="fa fa-check"></i><b>13.4</b> Summary<span></span></a></li>
<li class="chapter" data-level="13.5" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#practice"><i class="fa fa-check"></i><b>13.5</b> Practice<span></span></a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#our-question"><i class="fa fa-check"></i><b>13.5.1</b> Our question<span></span></a></li>
<li class="chapter" data-level="13.5.2" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#hypothesis"><i class="fa fa-check"></i><b>13.5.2</b> Hypothesis<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="anova---spring-week-five.html"><a href="anova---spring-week-five.html#importing-the-data"><i class="fa fa-check"></i><b>13.6</b> Importing the data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html"><i class="fa fa-check"></i><b>14</b> Multivariate linear models - Spring Week Six<span></span></a>
<ul>
<li class="chapter" data-level="14.1" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#multivariate-linear-models"><i class="fa fa-check"></i><b>14.1</b> Multivariate linear models<span></span></a></li>
<li class="chapter" data-level="14.2" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#factorial-linear-models"><i class="fa fa-check"></i><b>14.2</b> Factorial linear models<span></span></a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#data-summary"><i class="fa fa-check"></i><b>14.2.1</b> Data summary<span></span></a></li>
<li class="chapter" data-level="14.2.2" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#one-way-anova"><i class="fa fa-check"></i><b>14.2.2</b> One-way ANOVA<span></span></a></li>
<li class="chapter" data-level="14.2.3" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#testing-for-interactions"><i class="fa fa-check"></i><b>14.2.3</b> Testing for interactions<span></span></a></li>
<li class="chapter" data-level="14.2.4" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#model-estimates-and-confidence-intervals"><i class="fa fa-check"></i><b>14.2.4</b> Model estimates and confidence intervals<span></span></a></li>
<li class="chapter" data-level="14.2.5" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#anova-tables"><i class="fa fa-check"></i><b>14.2.5</b> ANOVA tables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#balancedunbalanced-designs"><i class="fa fa-check"></i><b>14.3</b> Balanced/Unbalanced designs<span></span></a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#practice-1"><i class="fa fa-check"></i><b>14.3.1</b> Practice<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#post-hoc"><i class="fa fa-check"></i><b>14.4</b> post-hoc<span></span></a></li>
<li class="chapter" data-level="14.5" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#continuous-linear-models"><i class="fa fa-check"></i><b>14.5</b> Continuous Linear Models<span></span></a></li>
<li class="chapter" data-level="14.6" data-path="multivariate-linear-models---spring-week-six.html"><a href="multivariate-linear-models---spring-week-six.html#summary-7"><i class="fa fa-check"></i><b>14.6</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html"><i class="fa fa-check"></i><b>15</b> Complexity in Linear Models - Spring Week Seven<span></span></a>
<ul>
<li class="chapter" data-level="15.1" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#designing-a-model"><i class="fa fa-check"></i><b>15.1</b> Designing a Model<span></span></a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#hypothesis-1"><i class="fa fa-check"></i><b>15.1.1</b> Hypothesis<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#checking-the-data"><i class="fa fa-check"></i><b>15.2</b> Checking the data<span></span></a></li>
<li class="chapter" data-level="15.3" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#designing-a-model-1"><i class="fa fa-check"></i><b>15.3</b> Designing a model<span></span></a></li>
<li class="chapter" data-level="15.4" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#model-checking-collinearity"><i class="fa fa-check"></i><b>15.4</b> Model checking &amp; collinearity<span></span></a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#data-transformations"><i class="fa fa-check"></i><b>15.4.1</b> Data transformations<span></span></a></li>
<li class="chapter" data-level="15.4.2" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#boxcox"><i class="fa fa-check"></i><b>15.4.2</b> BoxCox<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#model-selection"><i class="fa fa-check"></i><b>15.5</b> Model selection<span></span></a></li>
<li class="chapter" data-level="15.6" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#posthoc"><i class="fa fa-check"></i><b>15.6</b> Posthoc<span></span></a></li>
<li class="chapter" data-level="15.7" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#write-up"><i class="fa fa-check"></i><b>15.7</b> Write-up<span></span></a></li>
<li class="chapter" data-level="15.8" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#summary-8"><i class="fa fa-check"></i><b>15.8</b> Summary<span></span></a>
<ul>
<li class="chapter" data-level="15.8.1" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#checklist"><i class="fa fa-check"></i><b>15.8.1</b> Checklist<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15.9" data-path="complexity-in-linear-models---spring-week-seven.html"><a href="complexity-in-linear-models---spring-week-seven.html#supplementary-code"><i class="fa fa-check"></i><b>15.9</b> Supplementary code<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>16</b> Generalized Linear Models<span></span></a>
<ul>
<li class="chapter" data-level="16.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#motivation"><i class="fa fa-check"></i><b>16.1</b> Motivation<span></span></a></li>
<li class="chapter" data-level="16.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#generalised-linear-models-glms"><i class="fa fa-check"></i><b>16.2</b> Generalised Linear Models (GLMs)<span></span></a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#workflow-for-fitting-a-glm"><i class="fa fa-check"></i><b>16.2.1</b> Workflow for fitting a GLM<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression-for-count-data-or-rate-data"><i class="fa fa-check"></i><b>16.3</b> Poisson regression (for count data or rate data)<span></span></a></li>
<li class="chapter" data-level="16.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example-cuckoos"><i class="fa fa-check"></i><b>16.4</b> Example: Cuckoos<span></span></a></li>
<li class="chapter" data-level="16.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#estimates-and-intervals"><i class="fa fa-check"></i><b>16.5</b> Estimates and Intervals<span></span></a>
<ul>
<li class="chapter" data-level="16.5.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#interpretation"><i class="fa fa-check"></i><b>16.5.1</b> Interpretation<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#overdispersion"><i class="fa fa-check"></i><b>16.6</b> Overdispersion<span></span></a></li>
<li class="chapter" data-level="16.7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression-for-binary-data"><i class="fa fa-check"></i><b>16.7</b> Logistic regression (for binary data)<span></span></a>
<ul>
<li class="chapter" data-level="16.7.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#probability-from-a-binomial-model"><i class="fa fa-check"></i><b>16.7.1</b> Probability from a binomial model<span></span></a></li>
<li class="chapter" data-level="16.7.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#changes-in-probability"><i class="fa fa-check"></i><b>16.7.2</b> Changes in probability<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#predictions"><i class="fa fa-check"></i><b>16.8</b> Predictions<span></span></a>
<ul>
<li class="chapter" data-level="16.8.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#assumptions-1"><i class="fa fa-check"></i><b>16.8.1</b> Assumptions<span></span></a></li>
<li class="chapter" data-level="16.8.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#write-up-1"><i class="fa fa-check"></i><b>16.8.2</b> Write-up<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16.9" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#summary-9"><i class="fa fa-check"></i><b>16.9</b> Summary<span></span></a></li>
<li class="chapter" data-level="16.10" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#final-checklist"><i class="fa fa-check"></i><b>16.10</b> Final checklist<span></span></a></li>
</ul></li>
<li><a href="references.html#references">References<span></span></a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for Biologists - 5023Y</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="generalized-linear-models" class="section level1 hasAnchor" number="16">
<h1><span class="header-section-number">Chapter 16</span> Generalized Linear Models<a href="generalized-linear-models.html#generalized-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="motivation" class="section level2 hasAnchor" number="16.1">
<h2><span class="header-section-number">16.1</span> Motivation<a href="generalized-linear-models.html#motivation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous workshop we have seen that linear models are a powerful modelling tool.
However, we have to satisfy the following assumptions:</p>
<ol style="list-style-type: decimal">
<li>A <strong>linear</strong> relationship between predictors and the mean response value.</li>
<li>Variances are equal across all predicted values of the response (<strong>homoscedatic</strong>)</li>
<li>Errors are <strong>normally</strong> distributed.</li>
<li>Samples collected at <strong>random</strong>.</li>
<li>No omitted variables of importance</li>
</ol>
<p>If assumptions 1-3 are violated we can often <em>transform</em> our response variable
to try and fix this (Box-Cox &amp; transformation).
However, in a lot of other cases this is either not possible (e.g binary output)
or we want to explicitly model the underlying distribution (e.g count data).
Instead, we can use <em>Generalised</em> Linear Models (GLMs) that let us change the <em>error structure</em> (assumption 3) to something other than a normal distribution.</p>
</div>
<div id="generalised-linear-models-glms" class="section level2 hasAnchor" number="16.2">
<h2><span class="header-section-number">16.2</span> Generalised Linear Models (GLMs)<a href="generalized-linear-models.html#generalised-linear-models-glms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Generalised Linear Models</strong> (GLMs) have:</p>
<ol style="list-style-type: decimal">
<li>A linear predictor.</li>
<li>An <strong>error/variance structure</strong>.</li>
<li>A <strong>link function</strong> (like an ‘internal’ transformation).</li>
</ol>
<p>The first (1) should be familiar, its everything that comes after the <code>~</code> in a linear model formula. Or as an equation <span class="math inline">\(\beta_0 + \beta_1\)</span>. The second (2) should also be familiar, variance measures the error structure of the model <span class="math inline">\(\epsilon\)</span>. An ordinary least squares model uses the normal distribution, but <em>GLMs</em> are able to use a wider range of distributions including poisson, binomial and Gamma. The third component (3) is less familiar, the link function is the equivalent of a transformation in an ordinary least squares model. However, rather than transforming <em>the data</em>, we transform the predictions made by the linear predictors. Common link functions are log and square root.</p>
<div class="rmdnote">
<p>
<strong>Maximum Likelihood</strong> - Generalised Linear Models fit a regression line by finding the parameter values that best fit the model to the data. This is very similar to the way that ordinary least squares finds the line of best fit by reducing the sum of squared errors. In fact for data with normally distributed residuals, the particular form of maximum likelihood <strong>is</strong> least squares.
</p>
<p>
However the normal (gaussian) distribution will not be a good model for lots of other types of data, binary data, is a good example and one we will investigate in this workshop.
</p>
<p>
Maximum likelihood provides a more generalized approach to model fitting that includes, but is broader than, least squares.
</p>
<p>
An advantage of the least squares method we have been using is that we can generate precise equations for the fit of the line. In contrast the calculations for GLMs (which are beyond the scope of this course) are approximate, essentially multiple potential best fit lines are made and compared against each other.
</p>
<p>
You will see two main differences in a GLM output:
</p>
<p>
If the model is one where the mean and variance are calculated <em>separately</em> (e.g. for most normal distributions), unceratinty estimates use the <em>t</em> distribution; and when we compare complex to simplified models (using <code>anova()</code> or <code>drop1()</code>) we use the <em>F</em>-test.
</p>
<p>
However, when we provide distributions where the mean and variance are expected to change <em>together</em> (Poisson and Binomial), then we calculate uncertainty estimates using the <em>z</em> distribution, and compare models with the <em>chi-square</em> distribution.
</p>
</div>
<p>The simple linear regression model we have used so far is a special cases of a GLM:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="generalized-linear-models.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(height <span class="sc">~</span> weight)</span></code></pre></div>
<p>is equivalent to</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="generalized-linear-models.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glm</span>(height <span class="sc">~</span> weight, <span class="at">family=</span><span class="fu">gaussian</span>(<span class="at">link=</span>identity))</span></code></pre></div>
<p>Compared to <a href="https://www.rdocumentation.org/packages/stats/versions/3.5.1/topics/lm"><code>lm()</code></a>, the <a href="https://www.rdocumentation.org/packages/stats/versions/3.5.1/topics/glm"><code>glm()</code></a> function takes an additional argument called <a href="https://www.rdocumentation.org/packages/stats/versions/3.5.1/topics/family"><code>family</code></a>, which
specifies the error structure <strong>and</strong> link function.</p>
<p>The default <strong>link function</strong> for the normal (Gaussian) distribution is the <strong>identity</strong>, <em>where no transformation is needed</em>i.e. for mean <span class="math inline">\(\mu\)</span> we have:</p>
<p><span class="math display">\[
\mu = \beta_0 + \beta_1 X
\]</span></p>
<p>Defaults are usually good choices (shown in bold below):</p>
<table>
<thead>
<tr class="header">
<th align="center">Family</th>
<th align="center">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><code>gaussian</code></td>
<td align="center"><strong><code>identity</code></strong></td>
</tr>
<tr class="even">
<td align="center"><code>binomial</code></td>
<td align="center"><strong><code>logit</code></strong>, <code>probit</code> or <code>cloglog</code></td>
</tr>
<tr class="odd">
<td align="center"><code>poisson</code></td>
<td align="center"><strong><code>log</code></strong>, <code>identity</code> or <code>sqrt</code></td>
</tr>
<tr class="even">
<td align="center"><code>Gamma</code></td>
<td align="center"><strong><code>inverse</code></strong>, <code>identity</code> or <code>log</code></td>
</tr>
<tr class="odd">
<td align="center"><code>inverse.gaussian</code></td>
<td align="center"><strong><code>1/mu^2</code></strong></td>
</tr>
<tr class="even">
<td align="center"><code>quasibinomial</code></td>
<td align="center"><strong><code>logit</code></strong></td>
</tr>
<tr class="odd">
<td align="center"><code>quasipoisson</code></td>
<td align="center"><strong><code>log</code></strong></td>
</tr>
</tbody>
</table>
<details>
<summary>
<strong>EXERCISE - Using the fruitfly data introduced last week fit a linear model with lifespan as a response variable and sleep, type and thorax as explanatory variables. Compare this to a glm fitted with a gaussian error distribution and identity link for the mean</strong>
</summary>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="generalized-linear-models.html#cb27-1" aria-hidden="true" tabindex="-1"></a>flyls <span class="ot">&lt;-</span> <span class="fu">lm</span>(longevity <span class="sc">~</span> type <span class="sc">+</span> thorax <span class="sc">+</span> sleep, <span class="at">data =</span> fruitfly)</span>
<span id="cb27-2"><a href="generalized-linear-models.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flyls)</span></code></pre></div>
<pre><code>Call:
lm(formula = longevity ~ type + thorax + sleep, data = fruitfly)

Residuals:
    Min      1Q  Median      3Q     Max 
-28.153  -6.836  -2.191   7.196  29.046 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -56.04502   11.17882  -5.013 1.87e-06 ***
typeInseminated   3.62796    2.77122   1.309    0.193    
typeVirgin      -13.24603    2.76198  -4.796 4.70e-06 ***
thorax          144.43008   13.11616  11.012  &lt; 2e-16 ***
sleep            -0.05281    0.06383  -0.827    0.410    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 11.23 on 120 degrees of freedom
Multiple R-squared:  0.6046,    Adjusted R-squared:  0.5914 
F-statistic: 45.88 on 4 and 120 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="generalized-linear-models.html#cb29-1" aria-hidden="true" tabindex="-1"></a>flyglm <span class="ot">&lt;-</span> <span class="fu">glm</span>(longevity <span class="sc">~</span> type <span class="sc">+</span> thorax <span class="sc">+</span> sleep, </span>
<span id="cb29-2"><a href="generalized-linear-models.html#cb29-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">gaussian</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>),</span>
<span id="cb29-3"><a href="generalized-linear-models.html#cb29-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> fruitfly)</span>
<span id="cb29-4"><a href="generalized-linear-models.html#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flyglm)</span></code></pre></div>
<pre><code>glm(formula = longevity ~ type + thorax + sleep, family = gaussian(link = &quot;identity&quot;), 
    data = fruitfly)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-28.153   -6.836   -2.191    7.196   29.046  

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -56.04502   11.17882  -5.013 1.87e-06 ***
typeInseminated   3.62796    2.77122   1.309    0.193    
typeVirgin      -13.24603    2.76198  -4.796 4.70e-06 ***
thorax          144.43008   13.11616  11.012  &lt; 2e-16 ***
sleep            -0.05281    0.06383  -0.827    0.410    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for gaussian family taken to be 126.0381)

    Null deviance: 38253  on 124  degrees of freedom
Residual deviance: 15125  on 120  degrees of freedom
AIC: 966.2

Number of Fisher Scoring iterations: 2</code></pre>
<p>They are exactly the same. This is not surprising, as the maximum likelihood being fitted here is the same as an ordinary least squares model.</p>
</details>
<div id="workflow-for-fitting-a-glm" class="section level3 hasAnchor" number="16.2.1">
<h3><span class="header-section-number">16.2.1</span> Workflow for fitting a GLM<a href="generalized-linear-models.html#workflow-for-fitting-a-glm" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Exploratory data analysis</li>
<li>Choose suitable error term</li>
<li>Choose suitable mean function (and link function)</li>
<li>Fit model
<ul>
<li>Residual checks and model fit diagnostics</li>
<li>Revise model (transformations etc.)</li>
</ul></li>
<li>Model simplification if required</li>
<li>Check final model again</li>
</ul>
<div class="rmdnote">
<p>
When you transform your data e.g. with a log or sqrt, this changes the mean and variance at the same time (everything gets squished down). This might be fine, but can lead to difficult model fits if you need to reduce unequal variance but this leads to a change (often curvature) in the way the predictors fit to the response variable.
</p>
<p>
GLMs model the mean and variability independently. So a link function produces a transformation between predictors and the mean, and the relationship between the mean and data points is modelled separately.
</p>
</div>
</div>
</div>
<div id="poisson-regression-for-count-data-or-rate-data" class="section level2 hasAnchor" number="16.3">
<h2><span class="header-section-number">16.3</span> Poisson regression (for count data or rate data)<a href="generalized-linear-models.html#poisson-regression-for-count-data-or-rate-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Count or rate data are ubiquitous in the life sciences (e.g number of parasites per microlitre of blood, number of species counted in a particular area). These type of data are <strong>discrete</strong> and <strong>non-negative</strong>.
In such cases assuming our response variable to be normally distributed is not typically sensible.
The Poisson distribution lets us model count data explicitly.</p>
<p>Recall the simple linear regression case (i.e a GLM with a Gaussian error structure and identity link). For the sake of clarity let’s consider a single explanatory variable where <span class="math inline">\(\mu\)</span> is the mean for <em>Y</em>:</p>
<p><span class="math display">\[
\begin{aligned}
\mu &amp; = \beta_0 + \beta_1X
\end{aligned}
\]</span></p>
<p>The mean function is <strong>unconstrained</strong>, i.e the value of <span class="math inline">\(\beta_0 + \beta_1X\)</span> can range from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(+\infty\)</span>. If we want to model count data we therefore want to <strong>constrain</strong> this mean to be positive only. Mathematically we can do this by taking the <strong>logarithm</strong> of the mean (the log is the default link for the Poisson distribution). We then assume our count data variance to be Poisson distributed (a discrete, non-negative distribution), to obtain our Poisson regression model (to be consistent with the statistics literature we will rename <span class="math inline">\(\mu\)</span> to <span class="math inline">\(\lambda\)</span>):</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp; \sim \mathcal{Pois}(\lambda) \\
\log{\lambda} &amp; = \beta_0 + \beta_1X
\end{aligned}
\]</span></p>
<blockquote>
<p>Note - the relationship between the mean and the data is modelled by Poisson variance. The relationship between the predictors and the mean is modelled by a log transformation.</p>
</blockquote>
<p>The <strong>Poisson</strong> distribution has the following characteristics:</p>
<ul>
<li><strong>Discrete</strong> variable, defined on the range <span class="math inline">\(0, 1, \dots, \infty\)</span>.</li>
<li>A single <strong><em>rate</em></strong> parameter <span class="math inline">\(\lambda\)</span>, where <span class="math inline">\(\lambda &gt; 0\)</span>.</li>
<li><strong>Mean</strong> = <span class="math inline">\(\lambda\)</span><br />
</li>
<li><strong>Variance</strong> = <span class="math inline">\(\lambda\)</span></li>
</ul>
<p>So we model the variance as equal to the mean - as the mean increases so does the mean.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p><img src="images/poisson.png" title="Poisson distribution on an exponential line" alt="Poisson distribution on an exponential line" width="80%" /></p>
<p>So for the Poisson regression case we assume that the mean and variance are the same.
Hence, as the mean <em>increases</em>, the variance <em>increases</em> also (<strong>heteroscedascity</strong>).
This may or may not be a sensible assumption so watch out! Just because a Poisson distribution <em>usually</em> fits well for count data, doesn’t mean that a Gaussian distribution <em>can’t</em> always work.</p>
<p>Recall the link function between the predictors and the mean and the rules of logarithms (if <span class="math inline">\(\log{\lambda} = k\)</span>, then <span class="math inline">\(\lambda = e^k\)</span>):</p>
<p><span class="math display">\[
\begin{aligned}
\log{\lambda} &amp; = \beta_0 + \beta_1X \\
\lambda &amp; = e^{\beta_0 + \beta_1X }
\end{aligned}
\]</span>
Thus we are effectively modelling the observed counts (on the original scale) using an exponential mean function.</p>
</div>
<div id="example-cuckoos" class="section level2 hasAnchor" number="16.4">
<h2><span class="header-section-number">16.4</span> Example: Cuckoos<a href="generalized-linear-models.html#example-cuckoos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In a study by <a href="http://www.nature.com/nature/journal/v397/n6721/abs/397667a0.html">Kilner <em>et al.</em> (1999)</a>, the authors
studied the begging rate of nestlings in relation to total mass of the brood of <strong>reed warbler chicks</strong> and <strong>cuckoo chicks</strong>.
The question of interest is:</p>
<blockquote>
<p>How does nestling mass affect begging rates between the different species?</p>
</blockquote>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="generalized-linear-models.html#cb31-1" aria-hidden="true" tabindex="-1"></a>cuckoo <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/cuckoo.csv&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="generalized-linear-models.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cuckoo)</span></code></pre></div>
<p>The data columns are:</p>
<ul>
<li><strong>Mass</strong>: nestling mass of chick in grams</li>
<li><strong>Beg</strong>: begging calls per 6 secs</li>
<li><strong>Species</strong>: Warbler or Cuckoo</li>
</ul>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>There seem to be a relationship between mass and begging calls and it could
be different between species. It is tempting to fit a linear model to this data.
In fact, this is what the authors
of the original paper did; <strong>reed warbler chicks</strong> (solid circles, dashed fitted line) and
<strong>cuckoo chick</strong> (open circles, solid fitted line):</p>
<p><img src="images/original.png" width="505" /></p>
<p>This model is inadequate. It is predicting <strong>negative</strong> begging calls <em>within</em> the
range of the observed data, which clearly does not make any sense.</p>
<p>Let us display the model diagnostics plots for this linear model.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="generalized-linear-models.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Fit model</span></span>
<span id="cb33-2"><a href="generalized-linear-models.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="do">## There is an interaction term here, it is reasonable to think that how calling rates change with size might be different between the two species.</span></span>
<span id="cb33-3"><a href="generalized-linear-models.html#cb33-3" aria-hidden="true" tabindex="-1"></a>cuckoo_ls1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Beg <span class="sc">~</span> Mass<span class="sc">+</span>Species<span class="sc">+</span>Mass<span class="sc">:</span>Species, <span class="at">data=</span>cuckoo) </span></code></pre></div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="generalized-linear-models.html#cb34-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(cuckoo_ls1)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>The residuals plot depicts a strong “funnelling” effect, highlighting that the model assumptions are violated.
We should therefore try a different model structure.</p>
<p>The response variable in this case is a classic <strong>count data</strong>: <strong>discrete</strong> and bounded below by zero (i.e we cannot have negative counts). We will therefore try a <strong>Poisson model</strong> using the canonical <strong>log</strong> link function for the mean:</p>
<p><span class="math display">\[
    \log{\lambda} = \beta_0 + \beta_1 M_i + \beta_2 S_i + \beta_3 M_i S_i
\]</span></p>
<p>where <span class="math inline">\(M_i\)</span> is nestling mass and <span class="math inline">\(S_i\)</span> a <strong>dummy</strong> variable</p>
<p><span class="math display">\[
S_i = \left\{\begin{array}{ll}
        1 &amp; \mbox{if $i$ is warbler},\\
        0 &amp; \mbox{otherwise}.
        \end{array}
        \right.
\]</span></p>
<p>The term <span class="math inline">\(M_iS_i\)</span> is an <strong>interaction</strong> term. Think of this as an additional explanatory variable in our model.
Effectively it lets us have <strong>different</strong> slopes for different species (without an interaction term we assume that
both species have the same slope for the relationship between begging rate and mass, and only the intercept differ).</p>
<p>The mean regression lines for the two species look like this:</p>
<ul>
<li><strong>Cuckoo</strong> (<span class="math inline">\(S_i=0\)</span>)</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
    \log{\lambda} &amp; = \beta_0 + \beta_1 M_i + (\beta_2 \times 0)  + (\beta_3 \times M_i \times 0)\\
    \log{\lambda} &amp; = \beta_0 + \beta_1 M_i
\end{aligned}
\]</span></p>
<ul>
<li><p><strong>Intercept</strong> = <span class="math inline">\(\beta_0\)</span>, <strong>Gradient</strong> = <span class="math inline">\(\beta_1\)</span></p></li>
<li><p><strong>Warbler</strong> (<span class="math inline">\(S_i=1\)</span>)</p></li>
</ul>
$$
<span class="math display">\[\begin{aligned}
    \log{\lambda} &amp; = \beta_0 + \beta_1 M_i + (\beta_2 \times 1)  + (\beta_3 \times M_i \times 1)\\
    \log{\lambda} &amp; = \beta_0 + \beta_1 M_i + \beta_2 + \beta_3M_i\\
 
\end{aligned}\]</span>
<p>$$</p>
<p>Fit the model with the interaction term in R:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="generalized-linear-models.html#cb35-1" aria-hidden="true" tabindex="-1"></a>cuckoo_glm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Beg <span class="sc">~</span> Mass <span class="sc">+</span> Species <span class="sc">+</span> Mass<span class="sc">:</span>Species, <span class="at">data=</span>cuckoo, <span class="at">family=</span><span class="fu">poisson</span>(<span class="at">link=</span><span class="st">&quot;log&quot;</span>))</span>
<span id="cb35-2"><a href="generalized-linear-models.html#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="generalized-linear-models.html#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cuckoo_glm1)</span></code></pre></div>
<blockquote>
<p>Note there appears to be a negative interaction effect for Species:Mass, indicating that Begging calls do not increase with mass as much as you would expect for Warblers as compared to Cuckoos.</p>
</blockquote>
<p>Plot the mean regression line for each species:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="generalized-linear-models.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using augment allows you to generate fitted outcomes from the regression, make sure to set the predictions onto the response scale in order to &#39;back transform` the data onto the original scale</span></span>
<span id="cb36-2"><a href="generalized-linear-models.html#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="generalized-linear-models.html#cb36-3" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(cuckoo_glm1, <span class="at">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-4"><a href="generalized-linear-models.html#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Mass, <span class="at">y=</span>.fitted, <span class="at">colour=</span>Species)) <span class="sc">+</span> </span>
<span id="cb36-5"><a href="generalized-linear-models.html#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-6"><a href="generalized-linear-models.html#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb36-7"><a href="generalized-linear-models.html#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;turquoise3&quot;</span>))<span class="sc">+</span></span>
<span id="cb36-8"><a href="generalized-linear-models.html#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>We get an exponential curve in the scale of the original data, which is the <strong>same</strong> as a straight line in the log-scaled version of the data. So if we fit the same model without specifying <code>type.predict = "response"</code> Then we get the fitted generalized linear response.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="generalized-linear-models.html#cb37-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(cuckoo_glm1) <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="generalized-linear-models.html#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Mass, <span class="at">y=</span>.fitted, <span class="at">colour=</span>Species)) <span class="sc">+</span> </span>
<span id="cb37-3"><a href="generalized-linear-models.html#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb37-4"><a href="generalized-linear-models.html#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb37-5"><a href="generalized-linear-models.html#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;green3&quot;</span>,<span class="st">&quot;turquoise3&quot;</span>))<span class="sc">+</span></span>
<span id="cb37-6"><a href="generalized-linear-models.html#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>Compare the new Poisson model fits to the ordinary least squares model. We can see that although the homogeneity of variance is far from perfect, the curvature in the model has been drastically reduced (this makes sense as now we have a model fitted to exponential data), and the qqplot is within acceptable confidence intervals.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="generalized-linear-models.html#cb38-1" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">check_model</span>(cuckoo_glm1, </span>
<span id="cb38-2"><a href="generalized-linear-models.html#cb38-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">check =</span> <span class="fu">c</span>(<span class="st">&quot;homogeneity&quot;</span>,</span>
<span id="cb38-3"><a href="generalized-linear-models.html#cb38-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;qq&quot;</span>))</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="generalized-linear-models.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cuckoo_glm1)</span></code></pre></div>
<pre><code>Call:
glm(formula = Beg ~ Mass + Species + Mass:Species, family = poisson(link = &quot;log&quot;), 
    data = cuckoo)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-7.5178  -2.8298  -0.6672   1.5564   6.0631  

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)          0.334475   0.227143   1.473  0.14088    
Mass                 0.094847   0.007261  13.062  &lt; 2e-16 ***
SpeciesWarbler       0.674820   0.259217   2.603  0.00923 ** 
Mass:SpeciesWarbler -0.021673   0.008389  -2.584  0.00978 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 970.08  on 50  degrees of freedom
Residual deviance: 436.05  on 47  degrees of freedom
AIC: 615.83

Number of Fisher Scoring iterations: 6</code></pre>
<p>A reminder of how to interpret the regression coefficients of a model with an interaction term</p>
<ul>
<li><p>Intercept = <span class="math inline">\(\beta 0\)</span> (intercept for the <strong>reference* so here the </strong>log** of the mean number of begging calls for <strong>cuckoos</strong> when mass = 0)</p></li>
<li><p>Mass = <span class="math inline">\(\beta1\)</span> (slope: the change in the <strong>log</strong> mean count of begging calls for every gram of bodyweight for <strong>cuckoos</strong>)</p></li>
<li><p>SpeciesWarbler = <span class="math inline">\(\beta2\)</span> (the <strong>log</strong> mean increase/decrease in begging call rate of the <strong>warblers</strong> relative to cuckoos)</p></li>
<li><p>Mass:SpeciesWarbler =<span class="math inline">\(\beta3\)</span> (the <strong>log</strong> mean increase/decrease in the <strong>slope</strong> for <strong>warblers</strong> relative to cuckoos)</p></li>
</ul>
<blockquote>
<p>Note - because this is a Poisson distribution where variance is fixed with the mean we are using z scores. Estimates are on a log scale because of the link function - this means so are any S.E. or confidence intervals</p>
</blockquote>
</div>
<div id="estimates-and-intervals" class="section level2 hasAnchor" number="16.5">
<h2><span class="header-section-number">16.5</span> Estimates and Intervals<a href="generalized-linear-models.html#estimates-and-intervals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Remember that not only is this <strong>Poisson</strong> model fitting variance using a Poisson and not Normal distribution. It is also relating the predictors to the response variable with a “<em>log-link</em>” this means we need to exponentiate our estimates to get them on the same scale as the response (y) variable. Until you do this all the model estimates are logn(y).</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="generalized-linear-models.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(cuckoo_glm1)[<span class="dv">1</span>]) <span class="do">### Intercept - Incidence rate at Mass=0, and Species = Cuckoo</span></span>
<span id="cb41-2"><a href="generalized-linear-models.html#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="generalized-linear-models.html#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(cuckoo_glm1)[<span class="dv">2</span>]) <span class="do">### Change in the average incidence rate with Mass </span></span>
<span id="cb41-4"><a href="generalized-linear-models.html#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="generalized-linear-models.html#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(cuckoo_glm1)[<span class="dv">3</span>]) <span class="do">### Change in the incidence rate intercept when Species = Warbler and Mass = 0</span></span>
<span id="cb41-6"><a href="generalized-linear-models.html#cb41-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb41-7"><a href="generalized-linear-models.html#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(cuckoo_glm1)[<span class="dv">4</span>]) <span class="do">### The extra change in incidence rate for each unit increase in Mass when Species = Warbler (the interaction effect)</span></span></code></pre></div>
<p>Luckily when you tidy your models up with <code>broom</code> you can specify that you want to put model predictions on the response variable scale by specifying exponentiate=T which will remove the log transformation, and allow easy calculation of confidence intervals.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="generalized-linear-models.html#cb42-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(cuckoo_glm1, </span>
<span id="cb42-2"><a href="generalized-linear-models.html#cb42-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">exponentiate=</span>T, </span>
<span id="cb42-3"><a href="generalized-linear-models.html#cb42-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">conf.int=</span>T)</span></code></pre></div>
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
1.3972071
</td>
<td style="text-align:right;">
0.2271431
</td>
<td style="text-align:right;">
1.472531
</td>
<td style="text-align:right;">
0.1408775
</td>
<td style="text-align:right;">
0.8858795
</td>
<td style="text-align:right;">
2.1589962
</td>
</tr>
<tr>
<td style="text-align:left;">
Mass
</td>
<td style="text-align:right;">
1.0994905
</td>
<td style="text-align:right;">
0.0072615
</td>
<td style="text-align:right;">
13.061667
</td>
<td style="text-align:right;">
0.0000000
</td>
<td style="text-align:right;">
1.0841087
</td>
<td style="text-align:right;">
1.1154266
</td>
</tr>
<tr>
<td style="text-align:left;">
SpeciesWarbler
</td>
<td style="text-align:right;">
1.9636787
</td>
<td style="text-align:right;">
0.2592166
</td>
<td style="text-align:right;">
2.603304
</td>
<td style="text-align:right;">
0.0092330
</td>
<td style="text-align:right;">
1.1889064
</td>
<td style="text-align:right;">
3.2864493
</td>
</tr>
<tr>
<td style="text-align:left;">
Mass:SpeciesWarbler
</td>
<td style="text-align:right;">
0.9785598
</td>
<td style="text-align:right;">
0.0083890
</td>
<td style="text-align:right;">
-2.583559
</td>
<td style="text-align:right;">
0.0097787
</td>
<td style="text-align:right;">
0.9625068
</td>
<td style="text-align:right;">
0.9946969
</td>
</tr>
</tbody>
</table>
<div id="interpretation" class="section level3 hasAnchor" number="16.5.1">
<h3><span class="header-section-number">16.5.1</span> Interpretation<a href="generalized-linear-models.html#interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It is <strong>very important</strong> to remember whether you are describing the results on the log-link scale or the original scale. It would usually make more sense to provide answers on the original scale, but this means you must first exponentiate the relationshio between response predictors as described above when writing the results.</p>
<p>In this example we wished to infer the relationship between begging rates and mass in these two species.</p>
<p>I hypothesised that the rate of begging in chicks would increase as their body size increased. Interestingly I found there was a significant interaction effect with mass and species, where Warbler chicks increased their calling rate with mass at a rate that was only 0.98 [95%CI: 0.96-0.99] that of Cuckoo chicks (Poisson GLM: <span class="math inline">\(\chi^2\)</span><sub>1,47</sub> = 6.77, <em>P</em> = 0.009). This meant that while at hatching Warbler chicks start with a mean call rate that is higher than their parasitic brood mates, this quickly reverses as they grow.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="generalized-linear-models.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For a fixed  mean-variance model we use a Chisquare distribution</span></span>
<span id="cb43-2"><a href="generalized-linear-models.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(cuckoo_glm1, <span class="at">test =</span> <span class="st">&quot;Chisq&quot;</span>)</span>
<span id="cb43-3"><a href="generalized-linear-models.html#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="generalized-linear-models.html#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># emmeans can be another handy function - if you specify response then here it provideds the average call rate for each species, at the average value for any continuous measures - so here the average call rate for both species at an average body mass of 20.3</span></span>
<span id="cb43-5"><a href="generalized-linear-models.html#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="generalized-linear-models.html#cb43-6" aria-hidden="true" tabindex="-1"></a>emmeans<span class="sc">::</span><span class="fu">emmeans</span>(cuckoo_glm1, <span class="at">specs =</span> <span class="sc">~</span> Species<span class="sc">:</span>Mass, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="overdispersion" class="section level2 hasAnchor" number="16.6">
<h2><span class="header-section-number">16.6</span> Overdispersion<a href="generalized-linear-models.html#overdispersion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There is one <strong>extra</strong> check we need to apply to a Poisson model and that’s for <strong>overdispersion</strong></p>
<p>Poisson (and binomial models) assume that the variance is <em>equal to the mean.</em></p>
<p>However, if there is <strong>residual deviance that is bigger than the residual degrees of freedom</strong> then there is <em>more</em> variance than we expect from the prediction of the mean by our model.</p>
<p>Overdispersion can be diagnosed by <span class="math inline">\(\frac{residual~deviance}{residual~degrees~of~freedom}\)</span> which from our example here ‘summary()’ is <span class="math inline">\(\frac{436}{47} = 9.3\)</span></p>
<p>Overdispersion statistic values <strong>&gt; 1 = Overdispersed</strong></p>
<p>Overdispersion is a result of larger than expected variance for that mean under a Poisson distribution, this is clearly an issue with our model!</p>
<p>Luckily a simple fix is to fit a <em>quasi-likelihood</em> model which accounts for this, think of “quasi” as “sort of but not completely” Poisson.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="generalized-linear-models.html#cb44-1" aria-hidden="true" tabindex="-1"></a>cuckoo_glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Beg <span class="sc">~</span> Mass<span class="sc">+</span>Species<span class="sc">+</span>Mass<span class="sc">:</span>Species, <span class="at">data=</span>cuckoo, <span class="at">family=</span><span class="fu">quasipoisson</span>(<span class="at">link=</span><span class="st">&quot;log&quot;</span>))</span></code></pre></div>
<pre><code>Call:
glm(formula = Beg ~ Mass + Species + Mass:Species, family = quasipoisson(link = &quot;log&quot;), 
    data = cuckoo)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-7.5178  -2.8298  -0.6672   1.5564   6.0631  

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          0.33448    0.63129   0.530    0.599    
Mass                 0.09485    0.02018   4.700  2.3e-05 ***
SpeciesWarbler       0.67482    0.72043   0.937    0.354    
Mass:SpeciesWarbler -0.02167    0.02332  -0.930    0.357    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for quasipoisson family taken to be 7.7242)

    Null deviance: 970.08  on 50  degrees of freedom
Residual deviance: 436.05  on 47  degrees of freedom
AIC: NA

Number of Fisher Scoring iterations: 6</code></pre>
<p>As you can see, while none of the estimates have changed, the standard errors (and therefore our confidence intervals) have, this accounts for the greater than expected uncertainty we saw with the deviance, and applies a more cautious estimate of uncertainty. The interaction effect appears to no longer be significant at <span class="math inline">\(\alpha\)</span> = 0.05, now that we have wider standard errors.</p>
<blockquote>
<p>Note - because we are now estimating the variance again, the test statistics have reverted to <em>t</em> distributions and anova and drop1 functions should specify the F-test again.</p>
</blockquote>
<details>
<summary>
<strong>Question - How would you write up an Analysis Methods section?</strong>
</summary>
<p>I used a Poisson log-link Generalized Linear Model with quasi-likelihoods to account for overdispersion to analyse begging call rates in Warbler and Cuckoo chicks. The species of chick was included as a categorical predictor and mass was included as a continuous predictor.</p>
<p>The initial model also included an interaction term between species and mass, but this was removed from the final model as removal of this term did not significantly alter the fit of the model (ANOVA).</p>
<p>All analyses were carried out in R (ver 4.1.3) (R Core Team 2021) with the following packages; tidyverse (Wickham et al 2019), performance (Lüdecke et al 2021) for checking model assumptions, and MASS (Venables &amp; Ripley 2002) for model comparisons.</p>
</div>
<div id="logistic-regression-for-binary-data" class="section level2 hasAnchor" number="16.7">
<h2><span class="header-section-number">16.7</span> Logistic regression (for binary data)<a href="generalized-linear-models.html#logistic-regression-for-binary-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When our response variable is binary, we can use a glm with a <strong>binomial</strong> error distribution</p>
<p>So far we have only considered continuous and discrete data as response variables. What if our response is a categorical variable (e.g passing or failing an exam, voting yes or no in a referendum, whether an egg has successfully fledged or been predated, infected/uninfected, alive/dead)?</p>
<p>We can model the <strong>probability</strong> <span class="math inline">\(p\)</span> of being in a particular class as a function of other
explanatory variables.</p>
<p>These type of <strong>binary</strong> data are assumed to follow a <strong>Bernoulli</strong> distribution (which is a special case of <em>Binomial</em>) which has the following characteristics:</p>
<p><span class="math display">\[
Y \sim \mathcal{Bern}(p)
\]</span></p>
<ul>
<li><strong>Binary</strong> variable, taking the values 0 or 1 (yes/no, pass/fail).</li>
<li>A <strong>probability</strong> parameter <span class="math inline">\(p\)</span>, where <span class="math inline">\(0 &lt; p &lt; 1\)</span>.</li>
<li><strong>Mean</strong> = <span class="math inline">\(p\)</span><br />
</li>
<li><strong>Variance</strong> = <span class="math inline">\(p(1 - p)\)</span></li>
</ul>
<p>Let us now place the Gaussian (simple linear regression), Poisson and logistic models next to each other:</p>
<p><span class="math display">\[
\begin{aligned}
Y &amp; \sim \mathcal{N}(\mu, \sigma^2) &amp;&amp;&amp; Y  \sim \mathcal{Pois}(\lambda) &amp;&amp;&amp; Y  \sim \mathcal{Bern}(p)\\
\mu &amp; = \beta_0 + \beta_1X &amp;&amp;&amp; \log{\lambda} = \beta_0 + \beta_1X &amp;&amp;&amp; ?? = \beta_0 + \beta_1X
\end{aligned}
\]</span></p>
<p>Now we need to fill in the <code>??</code> with the appropriate term. Similar to the Poisson regression case,
we cannot simply model the probabiliy as <span class="math inline">\(p = \beta_0 + \beta_1X\)</span>, because <span class="math inline">\(p\)</span> <strong>cannot</strong> be negative.
<span class="math inline">\(\log{p} = \beta_0 + \beta_1X\)</span> won’t work either, because <span class="math inline">\(p\)</span> cannot be greater than 1. Instead we
model the <strong>log odds</strong> <span class="math inline">\(\log\left(\frac{p}{1 - p}\right)\)</span> as a linear function. So our logistic regression model looks
like this:</p>
<p><span class="math display">\[
\begin{aligned}
Y  &amp; \sim \mathcal{Bern}(p)\\
\log\left(\frac{p}{1 - p}\right) &amp;  = \beta_0 + \beta_1 X
\end{aligned}
\]</span></p>
<p>Again, note that we are still “only” fitting straight lines through our data, but this time in the log odds space.
As a shorthand notation we write <span class="math inline">\(\log\left(\frac{p}{1 - p}\right) = \text{logit}(p) = \beta_0 + \beta_1 X\)</span>.</p>
<p>We can also re-arrange the above equation so that we get an expression for <span class="math inline">\(p\)</span></p>
<p><span class="math display">\[
p = \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}}
\]</span></p>
<p>Note how <span class="math inline">\(p\)</span> can only vary between 0 and 1.</p>
<p>To implement the logistic regression model in R, we choose <code>family=binomial(link=logit)</code> (the Bernoulli distribution is a special case of the Binomial distribution).</p>
<pre><code>glm(response ~ explanatory, family=binomial(link=logit))</code></pre>
<p><a href="https://en.wikipedia.org/wiki/Space_Shuttle_Challenger_disaster#O-ring_concerns">The Challenger Disaster</a></p>
<p>In 1985, NASA made the decision to send the first civilian into space.</p>
<p>This decision brought a huge amount of public attention to the STS-51-L mission, which would be Challenger’s 25th trip to space and school teacher Christa McAuliffe’s 1st. On the afternoon of January 28th, 1986 students around America tuned in to watch McAuliffe and six other astronauts launch from Cape Canaveral, Florida. 73 seconds into the flight, the shuttle experienced a critical failure and broke apart in mid air, resulting in the deaths of all seven crewmembers: Christa McAuliffe, Dick Scobee, Judy Resnik, Ellison Onizuka, Ronald McNair, Gregory Jarvis, and Michael Smith.</p>
<p>After an investigation into the incident, it was discovered that the failure was caused by an O-ring in the solid rocket booster. Additionally, it was revealed that such an incident was foreseeable.</p>
<p>In this half of the worksheet we will discuss how the right statistical model could have predicted the critical failure of an O-ring on that day.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="generalized-linear-models.html#cb47-1" aria-hidden="true" tabindex="-1"></a>Challenger <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/Challenger.csv&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="generalized-linear-models.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Challenger)</span></code></pre></div>
<p>The data columns are:</p>
<ul>
<li><p><strong>oring_tot</strong>: Total number of orings on the flight</p></li>
<li><p><strong>oring_dt</strong> : number of orings that failed during a flight</p></li>
<li><p><strong>temp</strong>: Outside temperature on the date of the flight</p></li>
<li><p><strong>flight</strong> order of flights</p></li>
</ul>
<p>It was frequently discussed issue that temperature might play a role in the critical safety of the o-rings on the shuttles.
One of the biggest mistakes made in assessing the flight risk for the Challenger was to only look at the flights <strong>where a failure had occurred</strong></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="generalized-linear-models.html#cb49-1" aria-hidden="true" tabindex="-1"></a>Challenger <span class="sc">%&gt;%</span> </span>
<span id="cb49-2"><a href="generalized-linear-models.html#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(oring_dt <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="generalized-linear-models.html#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>oring_dt, <span class="at">x=</span>temp))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb49-4"><a href="generalized-linear-models.html#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Temperature on flight launches where an O-ring incident occurred&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>From this it was concluded that temperature did not appear to affect o-ring risk of failure, as o-ring failures were detected at a range of different temperatures.</p>
<p>However when we compare this to the full data that was available a very different picture emerges.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="generalized-linear-models.html#cb50-1" aria-hidden="true" tabindex="-1"></a>Challenger <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="generalized-linear-models.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span>oring_dt, </span>
<span id="cb50-3"><a href="generalized-linear-models.html#cb50-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">x=</span>temp))<span class="sc">+</span></span>
<span id="cb50-4"><a href="generalized-linear-models.html#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb50-5"><a href="generalized-linear-models.html#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>)<span class="sc">+</span></span>
<span id="cb50-6"><a href="generalized-linear-models.html#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;All launch data&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>When we include the flights without incident <em>and</em> those with incident, we can see that there is a very clear relationship between temperature and the risk of an o-ring failure. It has been argued that the clear presentation of this data should have allowed even the casual observer to determine the high risk of disaster.</p>
<p>However if we want to understand the actual relationship between temperature and risk then there are several issues with fitting a linear model here - once again the data is an integer, and bounded by zero (our model predicts negative failure rates within the observed data range).</p>
<p>We COULD consider this as suitable for a Poisson model - but if we are really interested in determining the binary risk of <strong>having a flight with o-ring failure vs. no failure</strong>. Then we should implement a GLM with a Binomial distribution.</p>
<p>We can use dplyr to generate a binary column of no incident ‘0’ and fail ‘1’ for anything &gt;0.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="generalized-linear-models.html#cb51-1" aria-hidden="true" tabindex="-1"></a>Challenger <span class="ot">&lt;-</span> Challenger <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="generalized-linear-models.html#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">oring_binary =</span> <span class="fu">ifelse</span>(oring_dt <span class="sc">==</span><span class="st">&#39;0&#39;</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<p>Fitting a binary GLM</p>
<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
23.7749552
</td>
<td style="text-align:right;">
11.8203514
</td>
<td style="text-align:right;">
2.011358
</td>
<td style="text-align:right;">
0.0442877
</td>
<td style="text-align:right;">
7.2430347
</td>
<td style="text-align:right;">
58.1947978
</td>
</tr>
<tr>
<td style="text-align:left;">
temp
</td>
<td style="text-align:right;">
-0.3667009
</td>
<td style="text-align:right;">
0.1751673
</td>
<td style="text-align:right;">
-2.093432
</td>
<td style="text-align:right;">
0.0363106
</td>
<td style="text-align:right;">
-0.8772585
</td>
<td style="text-align:right;">
-0.1217173
</td>
</tr>
</tbody>
</table>
<p>So we are now fitting the following model</p>
<p><span class="math display">\[
 Y \sim Bern(p)
\]</span>
<span class="math display">\[
\log\left[ \frac { P( \operatorname{oring\_binary} = fail) }{ 1 - P( \operatorname{oring\_binary} = fail) } \right] = \beta_{0} + \beta_{1}(\operatorname{temp})
\]</span>
Which in R will look like this:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="generalized-linear-models.html#cb52-1" aria-hidden="true" tabindex="-1"></a>binary_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(oring_binary<span class="sc">~</span>temp, <span class="at">family=</span>binomial, <span class="at">data=</span>Challenger)</span></code></pre></div>
<ul>
<li>Intercept = <span class="math inline">\(\beta_{0}\)</span> = 23.77</li>
</ul>
<p>When the temperature is 0°F the mean <em>log-odds</em> are 23.77 [95%CI: 7.24- 58.19] for a failure incident in the O-rings</p>
<ul>
<li>Temp = <span class="math inline">\(\beta_{1}\)</span> = -0.37 [95%CI: -0.87 - -0.12]</li>
</ul>
<p>For every rise in the temperature by 1°F, the <em>log-odds</em> of a critical incident fall by 0.37.</p>
<div id="probability-from-a-binomial-model" class="section level3 hasAnchor" number="16.7.1">
<h3><span class="header-section-number">16.7.1</span> Probability from a binomial model<a href="generalized-linear-models.html#probability-from-a-binomial-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we use the <code>emmeans()</code> function it will convert <em>log-odds</em> to estimate the probability of o-ring failure at the mean value of x (temperature).
But how does it do this?</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="generalized-linear-models.html#cb53-1" aria-hidden="true" tabindex="-1"></a>emmeans<span class="sc">::</span><span class="fu">emmeans</span>(binary_model, <span class="at">specs=</span><span class="sc">~</span>temp, <span class="at">type=</span><span class="st">&quot;response&quot;</span>)</span></code></pre></div>
<p>This is the equation to work out probability using the <strong>exponent</strong> of the linear regression equation:</p>
<p><span class="math display">\[
P(\operatorname{risk of failure at }  X=69)\left[ \frac{e^{23.77+(-0.37 \times 69.6)}}{1+e^{23.77+(-0.37 \times 69.6)}} \right]
\]</span></p>
<p>Which produces the following result and we can confirm the risk of an o-ring failure on an <em>average</em> day is 0.15</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="generalized-linear-models.html#cb54-1" aria-hidden="true" tabindex="-1"></a>estimate_at_69<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(binary_model)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(binary_model)[<span class="dv">2</span>]<span class="sc">*</span><span class="fl">69.6</span>)</span>
<span id="cb54-2"><a href="generalized-linear-models.html#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="generalized-linear-models.html#cb54-3" aria-hidden="true" tabindex="-1"></a>estimate_at_69<span class="fl">.6</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>estimate_at_69<span class="fl">.6</span>)</span></code></pre></div>
</div>
<div id="changes-in-probability" class="section level3 hasAnchor" number="16.7.2">
<h3><span class="header-section-number">16.7.2</span> Changes in probability<a href="generalized-linear-models.html#changes-in-probability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A useful <em>rule-of-thumb</em> can be the <strong>divide-by-four</strong> rule.</p>
<p>This can be described as the <strong>maximum</strong> difference in probability for a unit change in <span class="math inline">\(X\)</span> is <span class="math inline">\(\beta/4\)</span>.</p>
<p>In our example the <strong>maximum difference</strong> in probability from a one degree change in Temp is <span class="math inline">\(-0.37/4 = -0.09\)</span></p>
<p>So the <strong>maximum difference</strong> in probability of failure corresponding to a one degree change is 9%</p>
<p>If you want to augment your data with the model, you can use the <code>augment()</code> function, remembering to specify <code>type.predict = "response</code> to get probabilities of o-ring failure (not log odds).</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="generalized-linear-models.html#cb55-1" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">augment</span>(binary_model, <span class="at">type.predict=</span><span class="st">&quot;response&quot;</span>, <span class="at">se_fit =</span> T) </span></code></pre></div>
<p>Annoyingly a limitation of the augment function is that it won’t produce 95% CI for predictions on glms. But I have written a short function to do this
Don’t worry if this is a lot to get your head around - the main thing is use this code to produce 95% CI.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="generalized-linear-models.html#cb56-1" aria-hidden="true" tabindex="-1"></a>augment_glm <span class="ot">&lt;-</span> <span class="cf">function</span>(mod, <span class="at">predict =</span> <span class="cn">NULL</span>){</span>
<span id="cb56-2"><a href="generalized-linear-models.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  fam <span class="ot">&lt;-</span> <span class="fu">family</span>(mod)</span>
<span id="cb56-3"><a href="generalized-linear-models.html#cb56-3" aria-hidden="true" tabindex="-1"></a>  ilink <span class="ot">&lt;-</span> fam<span class="sc">$</span>linkinv</span>
<span id="cb56-4"><a href="generalized-linear-models.html#cb56-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb56-5"><a href="generalized-linear-models.html#cb56-5" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">augment</span>(mod, <span class="at">newdata =</span> predict, <span class="at">se_fit=</span>T)<span class="sc">%&gt;%</span></span>
<span id="cb56-6"><a href="generalized-linear-models.html#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">.lower =</span> <span class="fu">ilink</span>(.fitted <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>.se.fit),</span>
<span id="cb56-7"><a href="generalized-linear-models.html#cb56-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">.upper =</span> <span class="fu">ilink</span>(.fitted <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>.se.fit), </span>
<span id="cb56-8"><a href="generalized-linear-models.html#cb56-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">.fitted=</span><span class="fu">ilink</span>(.fitted))</span>
<span id="cb56-9"><a href="generalized-linear-models.html#cb56-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb56-10"><a href="generalized-linear-models.html#cb56-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-11"><a href="generalized-linear-models.html#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="fu">augment_glm</span>(binary_model)</span></code></pre></div>
<details>
<summary>
<strong>EXERCISE - Use the augment_glm function to make a ggplot of the changing probability of O-ring failure with temperature</strong>
</summary>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="generalized-linear-models.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment_glm</span>(binary_model) <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="generalized-linear-models.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>temp, <span class="at">y=</span>oring_binary))<span class="sc">+</span><span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>temp, <span class="at">y=</span>.fitted))<span class="sc">+</span></span>
<span id="cb57-3"><a href="generalized-linear-models.html#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>.lower, <span class="at">ymax=</span>.upper), <span class="at">alpha=</span><span class="fl">0.2</span>)</span></code></pre></div>
</details>
</div>
</div>
<div id="predictions" class="section level2 hasAnchor" number="16.8">
<h2><span class="header-section-number">16.8</span> Predictions<a href="generalized-linear-models.html#predictions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>On the day the Challenger launched the outside air temperature was 36°F</p>
<p>We can use augment to add our model to new data - and make predictions about the risk of o-ring failure</p>
<details>
<summary>
<strong>Question - make a new dataset with the temperature on the day of the Challenger launch - what was the probability of o-ring failure?</strong>
</summary>
<p>First - we make a new dataset with the temperature on the day of the Challenger Launch <strong>36°F</strong></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="generalized-linear-models.html#cb58-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">temp=</span><span class="dv">36</span>, <span class="at">oring_binary=</span><span class="dv">1</span>)</span>
<span id="cb58-2"><a href="generalized-linear-models.html#cb58-2" aria-hidden="true" tabindex="-1"></a>new_data</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##    temp oring_binary
##   &lt;dbl&gt;        &lt;dbl&gt;
## 1    36            1</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="generalized-linear-models.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment_glm</span>(binary_model, new_data)</span></code></pre></div>
<pre><code># A tibble: 1 x 6
   temp oring_binary .fitted .se.fit .lower .upper
  &lt;dbl&gt;        &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1    36            1    1.00    5.54  0.431   1.00</code></pre>
<p>We can see from our fitted model, an O-ring failure on the day of the Challenger launch could have been predicted with a probability of &gt;0.999 [95%CI: 0.43-1]</p>
</details>
<div id="assumptions-1" class="section level3 hasAnchor" number="16.8.1">
<h3><span class="header-section-number">16.8.1</span> Assumptions<a href="generalized-linear-models.html#assumptions-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The standard model checks for a binary model do not hold (check them), they are usually a mess! There are alternative methods of looking at how well your binary model works, but well not cover these here.</p>
</div>
<div id="write-up-1" class="section level3 hasAnchor" number="16.8.2">
<h3><span class="header-section-number">16.8.2</span> Write-up<a href="generalized-linear-models.html#write-up-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Analysis: I used a Binomial logit-link Generalized Linear Model to analyse the effect of temperature on the likelihood of O-ring failure.</p>
<p>All analyses were carried out in R (ver 4.1.3) (R Core Team 2021) with the following packages; tidyverse (Wickham et al 2019).</p>
<p>Results: I found a significant negative relationship between temperature and probability of o-ring failure (logit-odds = -0.37 [95%CI: -0.88 - -0.12], <em>z</em> = -2.1, d.f = 21, <em>P</em> = 0.036). At an average temperature of 69.6°F the probability of o-ring failure was estimated at 0.15[0.03-0.45], but this rose to a near certainty of failure 0.99[0.43-1] at 36°F.</p>
<blockquote>
<p>Note you could use drop1( test = “Chisq”) here, but as there is only one, continuous variable, we can also report directly from the summary table.</p>
</blockquote>
</div>
</div>
<div id="summary-9" class="section level2 hasAnchor" number="16.9">
<h2><span class="header-section-number">16.9</span> Summary<a href="generalized-linear-models.html#summary-9" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>GLMs</strong> are powerful and flexible.</p>
<p>They can be used to fit a wide variety of data types.</p>
<p>Model checking becomes trickier.</p>
<p>Extensions include:</p>
<ul>
<li><strong>mixed models</strong>;</li>
<li><strong>survival models</strong>;</li>
<li><strong>generalised additive models</strong> (GAMs).</li>
</ul>
</div>
<div id="final-checklist" class="section level2 hasAnchor" number="16.10">
<h2><span class="header-section-number">16.10</span> Final checklist<a href="generalized-linear-models.html#final-checklist" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="complexity-in-linear-models---spring-week-seven.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/14-Complexities-in-models.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
